INSERT INTO REVISTA (ID_REVISTA,ISSN,NOME_REVISTA)VALUES (SEQ_REVISTA.NEXTVAL, '1984-2902','Revista Brasileira de Sistemas de Informação');
INSERT INTO REVISTA (ID_REVISTA,ISSN,NOME_REVISTA) VALUES (SEQ_REVISTA.NEXTVAL, '2150-7988', 'International Journal of Computer Information Systems and Industrial Management Applications');



INSERT INTO PESQUISA VALUES(SEQ_PESQUISA.NEXTVAL,'Governança em SOA','Estagio Final');
INSERT INTO PESQUISA VALUES(SEQ_PESQUISA.NEXTVAL,'Segurança em Aplicações WEB baseadas em serviço','Estagio Inicial');
INSERT INTO PESQUISA VALUES(SEQ_PESQUISA.NEXTVAL,'Metodos ageis em SOA','Estagio intermediario');


INSERT INTO PROD_BIBLIO VALUES(SEQ_PROD_BIBLIO.NEXTVAL,NULL, 'A BUSINESS MODEL FOR MANAGING SOA  INITIATIVES', 'ARTIGO COMPLETO',1,30,7,2014);

INSERT INTO PROD_BIBLIO VALUES(SEQ_PROD_BIBLIO.NEXTVAL,
(SELECT ID_PESQUISA FROM PESQUISA WHERE NOME_PESQUISA='Segurança em Aplicações WEB baseadas em serviço')
, 'DATA  ACCESS CONTROL WITH IDENTITY PROPAGATION IN WEB APPLICATIONS BASED ON SERVICES','ARTIGO COMPLETO',1,15,1,2014);

INSERT INTO PROD_BIBLIO VALUES(SEQ_PROD_BIBLIO.NEXTVAL,NULL, 'A TOOL TO GENERATE NATURAL LANGUAGE TEXT FROM BUSINESS PROCESS MODELS','ARTIGO COMPLETO',1,8,NULL,2014);

INSERT INTO PROD_BIBLIO VALUES(SEQ_PROD_BIBLIO.NEXTVAL,NULL, 'INTELLIGOV - COMPLIANCE VERIFICATION OF SERVICE-ORIENTED ARCHITECTURES WITH ONTOLOGIES AND SEMANTIC RULES AND QUERIES', 'ARTIGO COMPLETO',402,409,1,2014);

INSERT INTO PROD_BIBLIO VALUES(SEQ_PROD_BIBLIO.NEXTVAL,
(SELECT ID_PESQUISA FROM PESQUISA WHERE NOME_PESQUISA='Metodos ageis em SOA')
, 'A  METHOD FOR SERVICE AGILE CONSTRUCTION','ARTIGO COMPLETO',566,577,1,2014);

INSERT INTO PROD_BIBLIO VALUES(SEQ_PROD_BIBLIO.NEXTVAL,NULL, 'A  TOOL TO SUPPORT DEPLOYMENT OF SCIENTIFIC SOFTWARE AS A SERVICE','ARTIGO COMPLETO',1,4,1,2014);

INSERT INTO PROD_BIBLIO VALUES(SEQ_PROD_BIBLIO.NEXTVAL,
(SELECT ID_PESQUISA FROM PESQUISA WHERE NOME_PESQUISA='Governança em SOA')
, ' SOA GOVERNANCE FROM  AN ENTERPRISE ARCHITECTURE VIEWPOINT','ARTIGO COMPLETO', 494,505,1,2014);

INSERT INTO PROD_BIBLIO VALUES(SEQ_PROD_BIBLIO.NEXTVAL,NULL, ' SITUATIONAL  APPLICATION GENERATION FROM BUSINESS PROCESS MODELS','ARTIGO COMPLETO', 578,583,1,2014);

INSERT INTO PROD_BIBLIO VALUES(SEQ_PROD_BIBLIO.NEXTVAL,NULL, 'ASPECT IDENTIFICATION IN BUSINESS PROCESS MODELS USING PROCESS MINING TECHNIQUES','ARTIGO COMPLETO',50,53,4,2014);

INSERT INTO PROD_BIBLIO VALUES(SEQ_PROD_BIBLIO.NEXTVAL,NULL, 'A  METHOD FOR BRIDGING THE GAP BETWEEN BUSINESS PROCESS MODELS AND SERVICES','ARTIGO COMPLETO',62,98,6,2013);

INSERT INTO PROD_BIBLIO VALUES(SEQ_PROD_BIBLIO.NEXTVAL,
(SELECT ID_PESQUISA FROM PESQUISA WHERE NOME_PESQUISA='Governança em SOA')
, 'Governance of Service-Oriented Architecture through the CommonGov Approach','ARTIGO COMPLETO',505,514,6,2014);

INSERT INTO PROD_BIBLIO VALUES (SEQ_PROD_BIBLIO.NEXTVAL,
(SELECT ID_PESQUISA FROM PESQUISA WHERE NOME_PESQUISA='Governança em SOA')
, 'CommonGOV: A consolidate approach for governance of service-oriented architecture', 'ARTIGO COMPLETO', 389, 394, NULL, 2012);




INSERT INTO PROD_BIBLIO_BASE VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='INTELLIGOV - COMPLIANCE VERIFICATION OF SERVICE-ORIENTED ARCHITECTURES WITH ONTOLOGIES AND SEMANTIC RULES AND QUERIES')
,(SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='Governance of Service-Oriented Architecture through the CommonGov Approach'));
INSERT INTO PROD_BIBLIO_BASE VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='Governance of Service-Oriented Architecture through the CommonGov Approach')
,(SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='CommonGOV: A consolidate approach for governance of service-oriented architecture'));


INSERT INTO PALAVRA_CHAVE VALUES (SEQ_PALAVRA.NEXTVAL, 'SEMANTIC RULES');
INSERT INTO PALAVRA_CHAVE VALUES (SEQ_PALAVRA.NEXTVAL, 'SEMANTIC QUERIES');
INSERT INTO PALAVRA_CHAVE VALUES (SEQ_PALAVRA.NEXTVAL, 'SERVICE-ORIENTED ARQUITECTURE (SOA)');
INSERT INTO PALAVRA_CHAVE VALUES (SEQ_PALAVRA.NEXTVAL,'ONTOLOGY');
INSERT INTO PALAVRA_CHAVE VALUES (SEQ_PALAVRA.NEXTVAL, 'GOVERNANCE');
INSERT INTO PALAVRA_CHAVE VALUES (SEQ_PALAVRA.NEXTVAL, 'SERVICES');
INSERT INTO PALAVRA_CHAVE VALUES (SEQ_PALAVRA.NEXTVAL, 'SOA');



INSERT INTO PROD_BIBLIO_PALAVRA_CHAVE VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='INTELLIGOV - COMPLIANCE VERIFICATION OF SERVICE-ORIENTED ARCHITECTURES WITH ONTOLOGIES AND SEMANTIC RULES AND QUERIES'),
(SELECT ID_PALAVRA_CHAVE FROM PALAVRA_CHAVE WHERE PALAVRA='SEMANTIC RULES'));
INSERT INTO PROD_BIBLIO_PALAVRA_CHAVE VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='INTELLIGOV - COMPLIANCE VERIFICATION OF SERVICE-ORIENTED ARCHITECTURES WITH ONTOLOGIES AND SEMANTIC RULES AND QUERIES'), 
(SELECT ID_PALAVRA_CHAVE FROM PALAVRA_CHAVE WHERE PALAVRA='SEMANTIC QUERIES'));
INSERT INTO PROD_BIBLIO_PALAVRA_CHAVE VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='INTELLIGOV - COMPLIANCE VERIFICATION OF SERVICE-ORIENTED ARCHITECTURES WITH ONTOLOGIES AND SEMANTIC RULES AND QUERIES'),
 (SELECT ID_PALAVRA_CHAVE FROM PALAVRA_CHAVE WHERE PALAVRA='SERVICE-ORIENTED ARQUITECTURE (SOA)'));
INSERT INTO PROD_BIBLIO_PALAVRA_CHAVE VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='INTELLIGOV - COMPLIANCE VERIFICATION OF SERVICE-ORIENTED ARCHITECTURES WITH ONTOLOGIES AND SEMANTIC RULES AND QUERIES'),
(SELECT ID_PALAVRA_CHAVE FROM PALAVRA_CHAVE WHERE PALAVRA='ONTOLOGY') );
INSERT INTO PROD_BIBLIO_PALAVRA_CHAVE VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='INTELLIGOV - COMPLIANCE VERIFICATION OF SERVICE-ORIENTED ARCHITECTURES WITH ONTOLOGIES AND SEMANTIC RULES AND QUERIES'),
 (SELECT ID_PALAVRA_CHAVE FROM PALAVRA_CHAVE WHERE PALAVRA='GOVERNANCE'));
INSERT INTO PROD_BIBLIO_PALAVRA_CHAVE VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='Governance of Service-Oriented Architecture through the CommonGov Approach'),
 (SELECT ID_PALAVRA_CHAVE FROM PALAVRA_CHAVE WHERE PALAVRA='SERVICES'));
INSERT INTO PROD_BIBLIO_PALAVRA_CHAVE VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='Governance of Service-Oriented Architecture through the CommonGov Approach'),
 (SELECT ID_PALAVRA_CHAVE FROM PALAVRA_CHAVE WHERE PALAVRA='GOVERNANCE'));
INSERT INTO PROD_BIBLIO_PALAVRA_CHAVE VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='Governance of Service-Oriented Architecture through the CommonGov Approach'),
 (SELECT ID_PALAVRA_CHAVE FROM PALAVRA_CHAVE WHERE PALAVRA='SERVICE-ORIENTED ARQUITECTURE (SOA)'));
INSERT INTO PROD_BIBLIO_PALAVRA_CHAVE VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='CommonGOV: A consolidate approach for governance of service-oriented architecture'),
 (SELECT ID_PALAVRA_CHAVE FROM PALAVRA_CHAVE WHERE PALAVRA='GOVERNANCE'));
INSERT INTO PROD_BIBLIO_PALAVRA_CHAVE VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='CommonGOV: A consolidate approach for governance of service-oriented architecture'),
 (SELECT ID_PALAVRA_CHAVE FROM PALAVRA_CHAVE WHERE PALAVRA='SOA'));

INSERT INTO SITUACAO VALUES(SEQ_SITUACAO.NEXTVAL,'EM ELABORACAO');
INSERT INTO SITUACAO VALUES(SEQ_SITUACAO.NEXTVAL,'ACEITA');
INSERT INTO SITUACAO VALUES(SEQ_SITUACAO.NEXTVAL,'REJEITADA');
INSERT INTO SITUACAO VALUES(SEQ_SITUACAO.NEXTVAL,'AGUARDANDO RESPOSTA');
INSERT INTO SITUACAO VALUES(SEQ_SITUACAO.NEXTVAL,'AJUSTES SAO NECESSARIOS');

INSERT INTO PROD_BIBLIO_HIST VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='A BUSINESS MODEL FOR MANAGING SOA  INITIATIVES'),
(SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='EM ELABORACAO')
,'16/10/2014');
INSERT INTO PROD_BIBLIO_HIST VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='DATA  ACCESS CONTROL WITH IDENTITY PROPAGATION IN WEB APPLICATIONS BASED ON SERVICES'),
 (SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='EM ELABORACAO')
 , '16/10/2014');
 INSERT INTO PROD_BIBLIO_HIST VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='A BUSINESS MODEL FOR MANAGING SOA  INITIATIVES')
,(SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='AGUARDANDO RESPOSTA'),
 '20/10/2014');
INSERT INTO PROD_BIBLIO_HIST VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='DATA  ACCESS CONTROL WITH IDENTITY PROPAGATION IN WEB APPLICATIONS BASED ON SERVICES'),
 (SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='AGUARDANDO RESPOSTA')
 , '18/10/2014');
INSERT INTO PROD_BIBLIO_HIST VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='A  TOOL TO SUPPORT DEPLOYMENT OF SCIENTIFIC SOFTWARE AS A SERVICE'), 
(SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='AGUARDANDO RESPOSTA')
, '19/10/2014');
INSERT INTO PROD_BIBLIO_HIST VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='A  TOOL TO SUPPORT DEPLOYMENT OF SCIENTIFIC SOFTWARE AS A SERVICE'),
 (SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='EM ELABORACAO')
 , '16/10/2014');
INSERT INTO PROD_BIBLIO_HIST VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='A TOOL TO GENERATE NATURAL LANGUAGE TEXT FROM BUSINESS PROCESS MODELS'), 
(SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='EM ELABORACAO')
, '16/10/2014');
INSERT INTO PROD_BIBLIO_HIST VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='INTELLIGOV - COMPLIANCE VERIFICATION OF SERVICE-ORIENTED ARCHITECTURES WITH ONTOLOGIES AND SEMANTIC RULES AND QUERIES'),
 (SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='EM ELABORACAO')
 , '16/10/2014');
INSERT INTO PROD_BIBLIO_HIST VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='A  METHOD FOR SERVICE AGILE CONSTRUCTION'), 
(SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='EM ELABORACAO')
, '16/10/2014');
INSERT INTO PROD_BIBLIO_HIST VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO=' SITUATIONAL  APPLICATION GENERATION FROM BUSINESS PROCESS MODELS'), 
(SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='AGUARDANDO RESPOSTA')
, '17/10/2014');
INSERT INTO PROD_BIBLIO_HIST VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO=' SOA GOVERNANCE FROM  AN ENTERPRISE ARCHITECTURE VIEWPOINT'), 
(SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='EM ELABORACAO')
, '16/10/2014');
INSERT INTO PROD_BIBLIO_HIST VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO=' SITUATIONAL  APPLICATION GENERATION FROM BUSINESS PROCESS MODELS'),
(SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='EM ELABORACAO')
, '16/10/2014');
INSERT INTO PROD_BIBLIO_HIST VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='ASPECT IDENTIFICATION IN BUSINESS PROCESS MODELS USING PROCESS MINING TECHNIQUES'),
 (SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='EM ELABORACAO')
 , '16/10/2014');
INSERT INTO PROD_BIBLIO_HIST VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='A  METHOD FOR BRIDGING THE GAP BETWEEN BUSINESS PROCESS MODELS AND SERVICES'), 
(SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='EM ELABORACAO')
, '16/10/2014');


INSERT INTO PROD_BIBLIO_HIST VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='ASPECT IDENTIFICATION IN BUSINESS PROCESS MODELS USING PROCESS MINING TECHNIQUES'),
(SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='AGUARDANDO RESPOSTA')
, '20/10/2014');
INSERT INTO PROD_BIBLIO_HIST VALUES ( (SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='CommonGOV: A consolidate approach for governance of service-oriented architecture')
,(SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='EM ELABORACAO')
,'10/10/2014');
INSERT INTO PROD_BIBLIO_HIST VALUES ( (SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='CommonGOV: A consolidate approach for governance of service-oriented architecture')
,(SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='AGUARDANDO RESPOSTA')
,'20/10/2014');


 
 
INSERT INTO EVENTO (ID_EVENTO,NOME_EVENTO,CLASSIFICACAO)VALUES (SEQ_EVENTO.NEXTVAL, ' Brazilian Congress in Software: Theory and Practice (CBSoft)', 'NACIONAL');
INSERT INTO EVENTO VALUES (SEQ_EVENTO.NEXTVAL, ' Brazilian Symposium in Information Systems (SBSI)','B4', 'NACIONAL');
INSERT INTO EVENTO VALUES (SEQ_EVENTO.NEXTVAL, 'Brazilian e-Science Workshop (BRESCI)','B5', 'NACIONAL');
INSERT INTO EVENTO (ID_EVENTO,NOME_EVENTO,CLASSIFICACAO)VALUES (SEQ_EVENTO.NEXTVAL, 'Workshop of Doctor and Master Thesis on Information Systems (WTDSI)', 'NACIONAL');
INSERT INTO EVENTO VALUES (SEQ_EVENTO.NEXTVAL, 'International Conference on Applied Computing','B4', 'INTERNACIONAL');
INSERT INTO EVENTO (ID_EVENTO,NOME_EVENTO,CLASSIFICACAO)VALUES (SEQ_EVENTO.NEXTVAL, 'Escola Regional de Informática do Rio de Janeiro', 'REGIONAL');
INSERT INTO EVENTO (ID_EVENTO,NOME_EVENTO,CLASSIFICACAO)VALUES (SEQ_EVENTO.NEXTVAL, 'Escola de Grid', 'LOCAL');
INSERT INTO EVENTO (ID_EVENTO,NOME_EVENTO,CLASSIFICACAO)VALUES (SEQ_EVENTO.NEXTVAL, 'Iberoamerican Meeting of Ontological Research', 'INTERNACIONAL');
INSERT INTO EVENTO (ID_EVENTO,NOME_EVENTO,CLASSIFICACAO)VALUES (SEQ_EVENTO.NEXTVAL, 'SBBD Demos', 'NACIONAL');
INSERT INTO EVENTO (ID_EVENTO,NOME_EVENTO,CLASSIFICACAO)VALUES (SEQ_EVENTO.NEXTVAL, 'International Workshop on Information Integration on the Web (WIIW)', 'INTERNACIONAL');
INSERT INTO EVENTO VALUES (SEQ_EVENTO.NEXTVAL, 'International Conference on Computational Aspects of Social Networks (CASoN)','B4', 'INTERNACIONAL');


INSERT INTO ESTADO VALUES (SEQ_ESTADO.NEXTVAL, 'RIO DE JANEIRO');
INSERT INTO ESTADO VALUES (SEQ_ESTADO.NEXTVAL, 'NORTH RHINE-WESTPHALIA');
INSERT INTO ESTADO VALUES (SEQ_ESTADO.NEXTVAL, 'TEXAS');
INSERT INTO ESTADO VALUES (SEQ_ESTADO.NEXTVAL, 'UTAH');
INSERT INTO ESTADO VALUES (SEQ_ESTADO.NEXTVAL, 'ALAGOAS');
INSERT INTO ESTADO VALUES (SEQ_ESTADO.NEXTVAL, 'SAO PAULO');
INSERT INTO ESTADO VALUES (SEQ_ESTADO.NEXTVAL, 'PARANA');
INSERT INTO ESTADO VALUES (SEQ_ESTADO.NEXTVAL, 'PARAIBA');
INSERT INTO ESTADO VALUES (SEQ_ESTADO.NEXTVAL, 'RIO GRANDE DO SUL');
INSERT INTO ESTADO VALUES (SEQ_ESTADO.NEXTVAL, 'SANTA CATARINA');
INSERT INTO ESTADO VALUES (SEQ_ESTADO.NEXTVAL, 'GEORGIA');



INSERT INTO PAIS VALUES (SEQ_PAIS.NEXTVAL, 'BRASIL');
INSERT INTO PAIS VALUES (SEQ_PAIS.NEXTVAL, 'ALEMANHA');
INSERT INTO PAIS VALUES (SEQ_PAIS.NEXTVAL, 'ESTADOS UNIDOS DA  AMERICA');
INSERT INTO PAIS VALUES (SEQ_PAIS.NEXTVAL, 'ARGENTINA');
INSERT INTO PAIS VALUES (SEQ_PAIS.NEXTVAL, 'URUGUAI');
INSERT INTO PAIS VALUES (SEQ_PAIS.NEXTVAL, 'PARAGUAI');
INSERT INTO PAIS VALUES (SEQ_PAIS.NEXTVAL, 'CANADA');
INSERT INTO PAIS VALUES (SEQ_PAIS.NEXTVAL, 'CHINA');
INSERT INTO PAIS VALUES (SEQ_PAIS.NEXTVAL, 'JAPAO');



INSERT INTO CIDADE VALUES (SEQ_CIDADE.NEXTVAL, (SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL'), 
(SELECT ID_ESTADO FROM ESTADO WHERE NOME_ESTADO='RIO DE JANEIRO')
, 'RIO DE JANEIRO');
INSERT INTO CIDADE VALUES (SEQ_CIDADE.NEXTVAL, (SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL'), 
(SELECT ID_ESTADO FROM ESTADO WHERE NOME_ESTADO='ALAGOAS')
, 'MACEIO');
INSERT INTO CIDADE VALUES (SEQ_CIDADE.NEXTVAL, (SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='ALEMANHA'),
 (SELECT ID_ESTADO FROM ESTADO WHERE NOME_ESTADO='NORTH RHINE-WESTPHALIA')
, 'HAGEN');
INSERT INTO CIDADE VALUES (SEQ_CIDADE.NEXTVAL, (SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL'),
(SELECT ID_ESTADO FROM ESTADO WHERE NOME_ESTADO='SAO PAULO')
, 'SAO PAULO');
INSERT INTO CIDADE VALUES (SEQ_CIDADE.NEXTVAL, (SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL'), 
(SELECT ID_ESTADO FROM ESTADO WHERE NOME_ESTADO='PARANA')
, 'LONDRINA');
INSERT INTO CIDADE VALUES (SEQ_CIDADE.NEXTVAL, (SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL'), 
(SELECT ID_ESTADO FROM ESTADO WHERE NOME_ESTADO='RIO GRANDE DO SUL'), 
'GRAMADO');
INSERT INTO CIDADE VALUES (SEQ_CIDADE.NEXTVAL, (SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL'),
(SELECT ID_ESTADO FROM ESTADO WHERE NOME_ESTADO='PARAIBA'),
 'JOAO PESSOA');
INSERT INTO CIDADE VALUES (SEQ_CIDADE.NEXTVAL, (SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL'), 
(SELECT ID_ESTADO FROM ESTADO WHERE NOME_ESTADO='RIO GRANDE DO SUL'),
 'PORTO ALEGRE');
INSERT INTO CIDADE VALUES (SEQ_CIDADE.NEXTVAL, (SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='ESTADOS UNIDOS DA  AMERICA'), 
(SELECT ID_ESTADO FROM ESTADO WHERE NOME_ESTADO='TEXAS'),
 'EL PASO');
INSERT INTO CIDADE VALUES (SEQ_CIDADE.NEXTVAL,(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='ESTADOS UNIDOS DA  AMERICA'), 
(SELECT ID_ESTADO FROM ESTADO WHERE NOME_ESTADO='UTAH'),
 'LOGAN');
INSERT INTO CIDADE VALUES (SEQ_CIDADE.NEXTVAL,(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='ESTADOS UNIDOS DA  AMERICA'),
(SELECT ID_ESTADO FROM ESTADO WHERE NOME_ESTADO='GEORGIA'),
 'ATLANTA');
INSERT INTO CIDADE VALUES (SEQ_CIDADE.NEXTVAL, (SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL'), 
(SELECT ID_ESTADO FROM ESTADO WHERE NOME_ESTADO='SAO PAULO'),
 'SAO CARLOS');




INSERT INTO EDICAO_EVENTO VALUES (SEQ_ED_EV.NEXTVAL,NULL
,(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO=' Brazilian Congress in Software: Theory and Practice (CBSoft)')
, 2012,(SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')) 
, 'I');
INSERT INTO EDICAO_EVENTO VALUES (SEQ_ED_EV.NEXTVAL,
(SELECT ID_EDICAO_EVENTO FROM EDICAO_EVENTO WHERE ID_EVENTO=(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO=' Brazilian Congress in Software: Theory and Practice (CBSoft)') AND ANO_EDICAO_EVENTO=2012)
,(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO=' Brazilian Congress in Software: Theory and Practice (CBSoft)')
, 2013,(SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL'))
, 'II');
INSERT INTO EDICAO_EVENTO VALUES (SEQ_ED_EV.NEXTVAL,
(SELECT ID_EDICAO_EVENTO FROM EDICAO_EVENTO WHERE ID_EVENTO=(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO=' Brazilian Congress in Software: Theory and Practice (CBSoft)') AND ANO_EDICAO_EVENTO=2013)
, (SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO=' Brazilian Congress in Software: Theory and Practice (CBSoft)')
, 2014,(SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='MACEIO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL'))
, 'III');
INSERT INTO EDICAO_EVENTO VALUES (SEQ_ED_EV.NEXTVAL,NULL,(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO='SBBD Demos')
, 2010,(SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL'))
, '25');
INSERT INTO EDICAO_EVENTO VALUES (SEQ_ED_EV.NEXTVAL,NULL, (SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO=' Brazilian Symposium in Information Systems (SBSI)')
, 2008,(SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL'))
, 'IV');
INSERT INTO EDICAO_EVENTO VALUES (SEQ_ED_EV.NEXTVAL,NULL,(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO='International Conference on Applied Computing')
, 2011,(SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL'))
, '8TH');
INSERT INTO EDICAO_EVENTO VALUES (SEQ_ED_EV.NEXTVAL,
(SELECT ID_EDICAO_EVENTO FROM EDICAO_EVENTO WHERE ID_EVENTO=(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO=' Brazilian Symposium in Information Systems (SBSI)') AND ANO_EDICAO_EVENTO=2008)
,(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO=' Brazilian Symposium in Information Systems (SBSI)')
, 2009,(SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='PORTO ALEGRE' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL'))
, 'V');
INSERT INTO EDICAO_EVENTO VALUES (SEQ_ED_EV.NEXTVAL,
(SELECT ID_EDICAO_EVENTO FROM EDICAO_EVENTO WHERE ID_EVENTO=(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO=' Brazilian Symposium in Information Systems (SBSI)') AND ANO_EDICAO_EVENTO=2009)
,(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO=' Brazilian Symposium in Information Systems (SBSI)')
, 2012,(SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='SAO PAULO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL'))
, 'VIII');
INSERT INTO EDICAO_EVENTO VALUES (SEQ_ED_EV.NEXTVAL,
(SELECT ID_EDICAO_EVENTO FROM EDICAO_EVENTO WHERE ID_EVENTO=(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO='International Conference on Applied Computing') AND ANO_EDICAO_EVENTO=2011)
,(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO='International Conference on Applied Computing'), 2014,
(SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL'))
, '11TH');
INSERT INTO EDICAO_EVENTO VALUES (SEQ_ED_EV.NEXTVAL,
(SELECT ID_EDICAO_EVENTO FROM EDICAO_EVENTO WHERE ID_EVENTO=(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO=' Brazilian Symposium in Information Systems (SBSI)') AND ANO_EDICAO_EVENTO=2012),
 (SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO=' Brazilian Symposium in Information Systems (SBSI)'), 2014
 ,(SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='MACEIO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL'))
 , 'X');
INSERT INTO EDICAO_EVENTO VALUES (SEQ_ED_EV.NEXTVAL,NULL,(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO= 'Workshop of Doctor and Master Thesis on Information Systems (WTDSI)'), 2014
,(SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='LONDRINA' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL'))
, 'V');
INSERT INTO EDICAO_EVENTO VALUES (SEQ_ED_EV.NEXTVAL,NULL, (SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO= 'Brazilian e-Science Workshop (BRESCI)'), 2014,
(SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='LONDRINA' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL'))
, 'VIII');
INSERT INTO EDICAO_EVENTO VALUES (SEQ_ED_EV.NEXTVAL,NULL, (SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO= 'International Conference on Computational Aspects of Social Networks (CASoN)')
, 2012,(SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='SAO CARLOS' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL'))
, 'FOURTH');



INSERT INTO PROD_BIBLIO_ED_EVENTO_SUBMETE VALUES(SEQ_PROD_BIBLIO_ED_EV_SUBMETE.NEXTVAL, (SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='A TOOL TO GENERATE NATURAL LANGUAGE TEXT FROM BUSINESS PROCESS MODELS')
, (SELECT ID_EDICAO_EVENTO FROM EDICAO_EVENTO WHERE ID_EVENTO=(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO=' Brazilian Congress in Software: Theory and Practice (CBSoft)') AND ANO_EDICAO_EVENTO=2014));
INSERT INTO PROD_BIBLIO_ED_EVENTO_SUBMETE VALUES(SEQ_PROD_BIBLIO_ED_EV_SUBMETE.NEXTVAL, (SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='A  METHOD FOR SERVICE AGILE CONSTRUCTION')
,( SELECT ID_EDICAO_EVENTO FROM EDICAO_EVENTO WHERE ID_EVENTO=(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO=' Brazilian Symposium in Information Systems (SBSI)') AND ANO_EDICAO_EVENTO=2014));
INSERT INTO PROD_BIBLIO_ED_EVENTO_SUBMETE VALUES(SEQ_PROD_BIBLIO_ED_EV_SUBMETE.NEXTVAL,(SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='A  TOOL TO SUPPORT DEPLOYMENT OF SCIENTIFIC SOFTWARE AS A SERVICE')
,( SELECT ID_EDICAO_EVENTO FROM EDICAO_EVENTO WHERE ID_EVENTO=(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO='Brazilian e-Science Workshop (BRESCI)') AND ANO_EDICAO_EVENTO=2014));
INSERT INTO PROD_BIBLIO_ED_EVENTO_SUBMETE VALUES(SEQ_PROD_BIBLIO_ED_EV_SUBMETE.NEXTVAL, (SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO=' SOA GOVERNANCE FROM  AN ENTERPRISE ARCHITECTURE VIEWPOINT')
, ( SELECT ID_EDICAO_EVENTO FROM EDICAO_EVENTO WHERE ID_EVENTO=(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO=' Brazilian Symposium in Information Systems (SBSI)') AND ANO_EDICAO_EVENTO=2014));
INSERT INTO PROD_BIBLIO_ED_EVENTO_SUBMETE VALUES(SEQ_PROD_BIBLIO_ED_EV_SUBMETE.NEXTVAL,(SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='ASPECT IDENTIFICATION IN BUSINESS PROCESS MODELS USING PROCESS MINING TECHNIQUES')
,(SELECT ID_EDICAO_EVENTO FROM EDICAO_EVENTO WHERE ID_EVENTO=(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO='Workshop of Doctor and Master Thesis on Information Systems (WTDSI)') AND ANO_EDICAO_EVENTO=2014));
INSERT INTO PROD_BIBLIO_ED_EVENTO_SUBMETE VALUES(SEQ_PROD_BIBLIO_ED_EV_SUBMETE.NEXTVAL,(SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='CommonGOV: A consolidate approach for governance of service-oriented architecture')
, (SELECT ID_EDICAO_EVENTO FROM EDICAO_EVENTO WHERE ID_EVENTO=(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO='International Conference on Computational Aspects of Social Networks (CASoN)') AND ANO_EDICAO_EVENTO=2012));



INSERT INTO SUBMETE_HIST VALUES ( (SELECT ID_SUBMISSAO FROM PROD_BIBLIO_ED_EVENTO_SUBMETE WHERE ID_PROD_BIBLIO=(SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='CommonGOV: A consolidate approach for governance of service-oriented architecture')
AND ID_EDICAO_EVENTO=(SELECT ID_EDICAO_EVENTO FROM EDICAO_EVENTO WHERE ID_EVENTO=(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO='International Conference on Computational Aspects of Social Networks (CASoN)') AND ANO_EDICAO_EVENTO=2012))
,(SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='AJUSTES SAO NECESSARIOS')
,'25/10/2014');
INSERT INTO SUBMETE_HIST VALUES ( (SELECT ID_SUBMISSAO FROM PROD_BIBLIO_ED_EVENTO_SUBMETE WHERE ID_PROD_BIBLIO=(SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='CommonGOV: A consolidate approach for governance of service-oriented architecture')
AND ID_EDICAO_EVENTO=(SELECT ID_EDICAO_EVENTO FROM EDICAO_EVENTO WHERE ID_EVENTO=(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO='International Conference on Computational Aspects of Social Networks (CASoN)') AND ANO_EDICAO_EVENTO=2012))
,(SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='ACEITA')
,'30/10/2014');
INSERT INTO SUBMETE_HIST VALUES ((SELECT ID_SUBMISSAO FROM PROD_BIBLIO_ED_EVENTO_SUBMETE WHERE ID_PROD_BIBLIO=(SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='A TOOL TO GENERATE NATURAL LANGUAGE TEXT FROM BUSINESS PROCESS MODELS')
AND ID_EDICAO_EVENTO=(SELECT ID_EDICAO_EVENTO FROM EDICAO_EVENTO WHERE ID_EVENTO=(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO=' Brazilian Congress in Software: Theory and Practice (CBSoft)') AND ANO_EDICAO_EVENTO=2014)), 
(SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='REJEITADA')
, '18/10/2014');
INSERT INTO SUBMETE_HIST VALUES ((SELECT ID_SUBMISSAO FROM PROD_BIBLIO_ED_EVENTO_SUBMETE WHERE ID_PROD_BIBLIO=(SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='A  METHOD FOR SERVICE AGILE CONSTRUCTION')
AND ID_EDICAO_EVENTO=(SELECT ID_EDICAO_EVENTO FROM EDICAO_EVENTO WHERE ID_EVENTO=(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO=' Brazilian Symposium in Information Systems (SBSI)') AND ANO_EDICAO_EVENTO=2014)), 
(SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='AJUSTES SAO NECESSARIOS')
, '17/10/2014');
INSERT INTO SUBMETE_HIST VALUES ((SELECT ID_SUBMISSAO FROM PROD_BIBLIO_ED_EVENTO_SUBMETE WHERE ID_PROD_BIBLIO=(SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO=' SOA GOVERNANCE FROM  AN ENTERPRISE ARCHITECTURE VIEWPOINT')
AND ID_EDICAO_EVENTO=(SELECT ID_EDICAO_EVENTO FROM EDICAO_EVENTO WHERE ID_EVENTO=(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO=' Brazilian Symposium in Information Systems (SBSI)') AND ANO_EDICAO_EVENTO=2014)),
 (SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='ACEITA')
 , '18/10/2014');
 INSERT INTO SUBMETE_HIST VALUES ((SELECT ID_SUBMISSAO FROM PROD_BIBLIO_ED_EVENTO_SUBMETE WHERE ID_PROD_BIBLIO=(SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='ASPECT IDENTIFICATION IN BUSINESS PROCESS MODELS USING PROCESS MINING TECHNIQUES')
AND ID_EDICAO_EVENTO=(SELECT ID_EDICAO_EVENTO FROM EDICAO_EVENTO WHERE ID_EVENTO=(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO='Workshop of Doctor and Master Thesis on Information Systems (WTDSI)') AND ANO_EDICAO_EVENTO=2014)),
 (SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='AJUSTES SAO NECESSARIOS')
 , '17/10/2014');
  INSERT INTO SUBMETE_HIST VALUES ((SELECT ID_SUBMISSAO FROM PROD_BIBLIO_ED_EVENTO_SUBMETE WHERE ID_PROD_BIBLIO=(SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='ASPECT IDENTIFICATION IN BUSINESS PROCESS MODELS USING PROCESS MINING TECHNIQUES')
AND ID_EDICAO_EVENTO=(SELECT ID_EDICAO_EVENTO FROM EDICAO_EVENTO WHERE ID_EVENTO=(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO='Workshop of Doctor and Master Thesis on Information Systems (WTDSI)') AND ANO_EDICAO_EVENTO=2014)),
 (SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='ACEITA')
 , '30/10/2014');
 INSERT INTO SUBMETE_HIST VALUES ( (SELECT ID_SUBMISSAO FROM PROD_BIBLIO_ED_EVENTO_SUBMETE WHERE ID_PROD_BIBLIO=(SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='A  TOOL TO SUPPORT DEPLOYMENT OF SCIENTIFIC SOFTWARE AS A SERVICE')
AND ID_EDICAO_EVENTO=(SELECT ID_EDICAO_EVENTO FROM EDICAO_EVENTO WHERE ID_EVENTO=(SELECT ID_EVENTO FROM EVENTO WHERE NOME_EVENTO='Brazilian e-Science Workshop (BRESCI)') AND ANO_EDICAO_EVENTO=2014)),
 (SELECT ID_SITUACAO FROM SITUACAO WHERE NOME_SITUACAO='ACEITA')
 , '19/10/2014');
 
 


INSERT INTO PESQUISADOR VALUES (SEQ_PESQUISADOR.NEXTVAL, 'LEONARDO', 'GUERREIRO', 'AZEVEDO', 2, '24 DE MAIO', 'RUA', 'APARTAMENTO 101');
INSERT INTO PESQUISADOR VALUES (SEQ_PESQUISADOR.NEXTVAL, 'FERNANDA', 'ARAUJO BAIAO', 'AMORIM', 5, 'DOM HÉLDER CÂMARA', 'AVENIDA', 'CASA 1');
INSERT INTO PESQUISADOR VALUES (SEQ_PESQUISADOR.NEXTVAL, 'FLAVIA', 'MARIA', 'SANTORO', 20, 'ATLÂNTICA', 'AVENIDA', 'APARTAMENTO 204');
INSERT INTO PESQUISADOR VALUES (SEQ_PESQUISADOR.NEXTVAL, 'HENRIQUE', 'PRADO', 'SOUSA', 8, 'BARATA RIBEIRO', 'RUA', 'APARTAMENTO 301');
INSERT INTO PESQUISADOR VALUES (SEQ_PESQUISADOR.NEXTVAL, 'JANO', 'MOREIRA', 'DE SOUZA', 64, 'DIAS DA CRUZ', 'RUA', 'CASA');
INSERT INTO PESQUISADOR VALUES (SEQ_PESQUISADOR.NEXTVAL, 'SEAN', 'WOLFGAND MATSUI', 'SIQUEIRA', 123, 'GOIÁS', 'RUA', 'FUNDOS');
INSERT INTO PESQUISADOR VALUES (SEQ_PESQUISADOR.NEXTVAL, 'JULIO CESAR', 'SAMPAIO DO PRADO', 'LEITE', 689, 'AYRTON SENNA', 'AVENIDA', 'APARTAMENTO 102');
INSERT INTO PESQUISADOR VALUES (SEQ_PESQUISADOR.NEXTVAL, 'THAIS', 'VASCONCELOS', 'BATISTA', 543, 'GEREMÁRIO DANTAS', 'AVENIDA', 'CASA 2');
INSERT INTO PESQUISADOR VALUES (SEQ_PESQUISADOR.NEXTVAL, 'KATE', 'CERQUEIRA', 'REVOREDO', 584, 'CLARIMUNDO DE MELO', 'RUA', 'CASA 7');
INSERT INTO PESQUISADOR VALUES (SEQ_PESQUISADOR.NEXTVAL, 'JONAS', 'FURTADO', 'DIAS', 1098, 'ARMANDO LOMBARDI', 'AVENIDA', 'COBERTURA');


INSERT INTO PESQUISADOR VALUES (SEQ_PESQUISADOR.NEXTVAL, 'THAISSA', 'DIIRR PINTO DE', 'MEDEIROS', 1, '24 DE MAIO', 'RUA', 'APARTAMENTO 304');
INSERT INTO PESQUISADOR VALUES (SEQ_PESQUISADOR.NEXTVAL, 'MARTA', 'LIMA DE QUEIROS', 'MATTOSO', 387, 'DOM HÉLDER CÂMARA', 'AVENIDA', 'CASA 2');
INSERT INTO PESQUISADOR VALUES (SEQ_PESQUISADOR.NEXTVAL, 'KARY', 'ANN DEL CARMEN SORIANO', 'OCANA', 645, 'ATLÂNTICA', 'AVENIDA', 'CASA 4');
INSERT INTO PESQUISADOR VALUES (SEQ_PESQUISADOR.NEXTVAL, 'EDUARDO', 'SOARES', 'OGASAWARA', 1098, 'BARATA RIBEIRO', 'RUA', 'CASA 3');
INSERT INTO PESQUISADOR VALUES (SEQ_PESQUISADOR.NEXTVAL, 'DANIEL', 'CARDOSO DE', 'OLIVEIRA', 457, 'DIAS DA CRUZ', 'RUA', 'APARTAMENTO 107');
INSERT INTO PESQUISADOR VALUES (SEQ_PESQUISADOR.NEXTVAL, 'DANIEL', 'CARDOSO MORAES DE', 'OLIVEIRA', 39, 'GOIÁS', 'RUA', 'APARTAMENTO 387');
INSERT INTO PESQUISADOR VALUES (SEQ_PESQUISADOR.NEXTVAL, 'ASTERIO', 'KIYOSHI', 'TANAKA', 4848, 'AYRTON SENNA', 'AVENIDA', 'COBERTURA');
INSERT INTO PESQUISADOR VALUES (SEQ_PESQUISADOR.NEXTVAL, 'RENATA', 'MENDES DE', 'ARAUJO', 8373, 'GEREMÁRIO DANTAS', 'AVENIDA', 'CASA 29');
INSERT INTO PESQUISADOR VALUES (SEQ_PESQUISADOR.NEXTVAL, 'VANESSA', 'TAVARES', 'NUNES', 6, 'CLARIMUNDO DE MELO', 'RUA', 'CASA');
INSERT INTO PESQUISADOR VALUES (SEQ_PESQUISADOR.NEXTVAL, 'HAROLDO', 'MARIA TEIXEIRA', 'FILHO', 873, 'ARMANDO LOMBARDI', 'AVENIDA', 'BLOCO 2, APARTAMENTO 208');
INSERT INTO PESQUISADOR VALUES (SEQ_PESQUISADOR.NEXTVAL, 'ALEXANDRE',NULL, 'SOUZA', 234, 'NILO PACANHA', 'AVENIDA', 'BLOCO 4, APARTAMENTO 101');
INSERT INTO PESQUISADOR VALUES (SEQ_PESQUISADOR.NEXTVAL, 'JAIRO', 'FRANCISCO', 'DE SOUSA', 654, 'GOIAS', 'RUA', 'CASA');



INSERT INTO PESQUISADOR_CIDADE_RESIDE VALUES ((SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')),
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='LEONARDO' AND NOME_DO_MEIO='GUERREIRO' AND ULTIMO_NOME='AZEVEDO'));
INSERT INTO PESQUISADOR_CIDADE_RESIDE VALUES ((SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')),
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='FERNANDA' AND NOME_DO_MEIO='ARAUJO BAIAO' AND ULTIMO_NOME='AMORIM'));
INSERT INTO PESQUISADOR_CIDADE_RESIDE VALUES ((SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')),
 (SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='FLAVIA' AND NOME_DO_MEIO='MARIA' AND ULTIMO_NOME='SANTORO'));
INSERT INTO PESQUISADOR_CIDADE_RESIDE VALUES ((SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')),
 (SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='HENRIQUE' AND NOME_DO_MEIO='PRADO' AND ULTIMO_NOME='SOUSA'));
INSERT INTO PESQUISADOR_CIDADE_RESIDE VALUES ((SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')), 
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='JANO' AND NOME_DO_MEIO='MOREIRA' AND ULTIMO_NOME='DE SOUZA'));
INSERT INTO PESQUISADOR_CIDADE_RESIDE VALUES ((SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')),
 (SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='SEAN' AND NOME_DO_MEIO='WOLFGAND MATSUI' AND ULTIMO_NOME='SIQUEIRA'));
INSERT INTO PESQUISADOR_CIDADE_RESIDE VALUES ((SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')),
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='JULIO CESAR' AND NOME_DO_MEIO='SAMPAIO DO PRADO' AND ULTIMO_NOME='LEITE'));
INSERT INTO PESQUISADOR_CIDADE_RESIDE VALUES ((SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')),
 (SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='THAIS' AND NOME_DO_MEIO='VASCONCELOS' AND ULTIMO_NOME='BATISTA'));
INSERT INTO PESQUISADOR_CIDADE_RESIDE VALUES ((SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')),
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='KATE' AND NOME_DO_MEIO='CERQUEIRA' AND ULTIMO_NOME='REVOREDO'));
INSERT INTO PESQUISADOR_CIDADE_RESIDE VALUES ((SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')),
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='JONAS' AND NOME_DO_MEIO='FURTADO' AND ULTIMO_NOME='DIAS'));
INSERT INTO PESQUISADOR_CIDADE_RESIDE VALUES ((SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')),
 (SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='THAISSA' AND NOME_DO_MEIO='DIIRR PINTO DE' AND ULTIMO_NOME='MEDEIROS'));
INSERT INTO PESQUISADOR_CIDADE_RESIDE VALUES ((SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')),
 (SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='MARTA' AND NOME_DO_MEIO='LIMA DE QUEIROS' AND ULTIMO_NOME='MATTOSO'));
INSERT INTO PESQUISADOR_CIDADE_RESIDE VALUES ((SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')),
  (SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='KARY' AND NOME_DO_MEIO='ANN DEL CARMEN SORIANO' AND ULTIMO_NOME='OCANA'));
INSERT INTO PESQUISADOR_CIDADE_RESIDE VALUES ((SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')),
 (SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='EDUARDO' AND NOME_DO_MEIO='SOARES' AND ULTIMO_NOME='OGASAWARA'));
INSERT INTO PESQUISADOR_CIDADE_RESIDE VALUES ((SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')),
 (SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='DANIEL' AND NOME_DO_MEIO='CARDOSO DE' AND ULTIMO_NOME='OLIVEIRA'));
INSERT INTO PESQUISADOR_CIDADE_RESIDE VALUES ((SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')),
 (SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='DANIEL' AND NOME_DO_MEIO='CARDOSO MORAES DE' AND ULTIMO_NOME='OLIVEIRA'));
INSERT INTO PESQUISADOR_CIDADE_RESIDE VALUES ((SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')),
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='ASTERIO' AND NOME_DO_MEIO='KIYOSHI' AND ULTIMO_NOME='TANAKA'));
INSERT INTO PESQUISADOR_CIDADE_RESIDE VALUES ((SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')),
 (SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='RENATA' AND NOME_DO_MEIO='MENDES DE' AND ULTIMO_NOME='ARAUJO'));
INSERT INTO PESQUISADOR_CIDADE_RESIDE VALUES ((SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')),
 (SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='VANESSA' AND NOME_DO_MEIO='TAVARES' AND ULTIMO_NOME='NUNES'));
INSERT INTO PESQUISADOR_CIDADE_RESIDE VALUES ((SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')),
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='HAROLDO' AND NOME_DO_MEIO='MARIA TEIXEIRA' AND ULTIMO_NOME='FILHO'));
INSERT INTO PESQUISADOR_CIDADE_RESIDE VALUES ((SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')),
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='ALEXANDRE' AND NOME_DO_MEIO IS NULL AND ULTIMO_NOME='SOUZA'));
INSERT INTO PESQUISADOR_CIDADE_RESIDE VALUES ((SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='LONDRINA' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')),
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='JAIRO' AND NOME_DO_MEIO='FRANCISCO' AND ULTIMO_NOME='DE SOUSA'));



INSERT INTO PROD_BIBLIO_PESQ_ESCREVE VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='Governance of Service-Oriented Architecture through the CommonGov Approach'), 
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='LEONARDO' AND NOME_DO_MEIO='GUERREIRO' AND ULTIMO_NOME='AZEVEDO'), 2);
INSERT INTO PROD_BIBLIO_PESQ_ESCREVE VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='Governance of Service-Oriented Architecture through the CommonGov Approach'),
 (SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='HAROLDO' AND NOME_DO_MEIO='MARIA TEIXEIRA' AND ULTIMO_NOME='FILHO'), 1);
INSERT INTO PROD_BIBLIO_PESQ_ESCREVE VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='CommonGOV: A consolidate approach for governance of service-oriented architecture'),
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='LEONARDO' AND NOME_DO_MEIO='GUERREIRO' AND ULTIMO_NOME='AZEVEDO'), 2);
INSERT INTO PROD_BIBLIO_PESQ_ESCREVE VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='CommonGOV: A consolidate approach for governance of service-oriented architecture'), 
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='HAROLDO' AND NOME_DO_MEIO='MARIA TEIXEIRA' AND ULTIMO_NOME='FILHO'), 1);


INSERT INTO COMENTARIO VALUES (SEQ_COMENT.NEXTVAL, (SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='CommonGOV: A consolidate approach for governance of service-oriented architecture'),
 (SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='FLAVIA' AND NOME_DO_MEIO='MARIA' AND ULTIMO_NOME='SANTORO'), '14/10/2014', 'VERIFICAR AS REFERÊNCIAS E A FORMATAÇÃO DO ARTIGO.');
INSERT INTO COMENTARIO VALUES (SEQ_COMENT.NEXTVAL, (SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='CommonGOV: A consolidate approach for governance of service-oriented architecture'),
 (SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='HENRIQUE' AND NOME_DO_MEIO='PRADO' AND ULTIMO_NOME='SOUSA'), '13/10/2014', 'VERIFICAR A FORMATAÇÃO DO ARTIGO.');
INSERT INTO COMENTARIO VALUES (SEQ_COMENT.NEXTVAL, (SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='CommonGOV: A consolidate approach for governance of service-oriented architecture'),
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='JANO' AND NOME_DO_MEIO='MOREIRA' AND ULTIMO_NOME='DE SOUZA'), '12/10/2014', 'VERIFICAR AS REFERÊNCIAS.');


INSERT INTO AFILIACAO VALUES (SEQ_AFILIACAO.NEXTVAL, (SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')), 'UNIVERSIDADE FEDERAL DO ESTADO DO RIO DE JANEIRO', 'GRADUAÇÃO', 'PASTEUR', 'AVENIDA', 296, 'CCET');
INSERT INTO AFILIACAO VALUES (SEQ_AFILIACAO.NEXTVAL,(SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')), 'IBM', 'PESQUISA', 'PASTEUR', 'AVENIDA', 20, NULL);
INSERT INTO AFILIACAO VALUES (SEQ_AFILIACAO.NEXTVAL,(SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')),'PETROBRAS | PETROLEO BRASILEIRO S/A', 'PESQUISA', 'GENERAL CANABARRO','RUA',500,'4º ANDAR');
INSERT INTO AFILIACAO VALUES (SEQ_AFILIACAO.NEXTVAL,(SELECT ID_CIDADE FROM CIDADE WHERE NOME_CIDADE='RIO DE JANEIRO' AND ID_PAIS=(SELECT ID_PAIS FROM PAIS WHERE NOME_PAIS='BRASIL')),'PONTIFICIA UNIVERSIDADE CATOLICA DO RIO DE JANEIRO', 'GRADUAÇÃO','MARQUÊS DE SÃO VICENTE', 'RUA', 225,NULL);


INSERT INTO PESQUISADOR_AFILIACAO_POSSUI VALUES ((SELECT ID_AFILIACAO FROM AFILIACAO WHERE NOME_AFILIACAO='UNIVERSIDADE FEDERAL DO ESTADO DO RIO DE JANEIRO'), 
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='LEONARDO' AND NOME_DO_MEIO='GUERREIRO' AND ULTIMO_NOME='AZEVEDO'));
INSERT INTO PESQUISADOR_AFILIACAO_POSSUI VALUES ((SELECT ID_AFILIACAO FROM AFILIACAO WHERE NOME_AFILIACAO='UNIVERSIDADE FEDERAL DO ESTADO DO RIO DE JANEIRO'),
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='FERNANDA' AND NOME_DO_MEIO='ARAUJO BAIAO' AND ULTIMO_NOME='AMORIM'));
INSERT INTO PESQUISADOR_AFILIACAO_POSSUI VALUES ((SELECT ID_AFILIACAO FROM AFILIACAO WHERE NOME_AFILIACAO='UNIVERSIDADE FEDERAL DO ESTADO DO RIO DE JANEIRO'),
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='FLAVIA' AND NOME_DO_MEIO='MARIA' AND ULTIMO_NOME='SANTORO'));
INSERT INTO PESQUISADOR_AFILIACAO_POSSUI VALUES ((SELECT ID_AFILIACAO FROM AFILIACAO WHERE NOME_AFILIACAO='UNIVERSIDADE FEDERAL DO ESTADO DO RIO DE JANEIRO'),
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='SEAN' AND NOME_DO_MEIO='WOLFGAND MATSUI' AND ULTIMO_NOME='SIQUEIRA'));
INSERT INTO PESQUISADOR_AFILIACAO_POSSUI VALUES ((SELECT ID_AFILIACAO FROM AFILIACAO WHERE NOME_AFILIACAO='UNIVERSIDADE FEDERAL DO ESTADO DO RIO DE JANEIRO'),
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='KATE' AND NOME_DO_MEIO='CERQUEIRA' AND ULTIMO_NOME='REVOREDO'));
INSERT INTO PESQUISADOR_AFILIACAO_POSSUI VALUES ((SELECT ID_AFILIACAO FROM AFILIACAO WHERE NOME_AFILIACAO='UNIVERSIDADE FEDERAL DO ESTADO DO RIO DE JANEIRO'), 
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='ASTERIO' AND NOME_DO_MEIO='KIYOSHI' AND ULTIMO_NOME='TANAKA'));
INSERT INTO PESQUISADOR_AFILIACAO_POSSUI VALUES ((SELECT ID_AFILIACAO FROM AFILIACAO WHERE NOME_AFILIACAO='UNIVERSIDADE FEDERAL DO ESTADO DO RIO DE JANEIRO'),
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='RENATA' AND NOME_DO_MEIO='MENDES DE' AND ULTIMO_NOME='ARAUJO'));
INSERT INTO PESQUISADOR_AFILIACAO_POSSUI VALUES ((SELECT ID_AFILIACAO FROM AFILIACAO WHERE NOME_AFILIACAO='UNIVERSIDADE FEDERAL DO ESTADO DO RIO DE JANEIRO'),
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='HAROLDO' AND NOME_DO_MEIO='MARIA TEIXEIRA' AND ULTIMO_NOME='FILHO'));
INSERT INTO PESQUISADOR_AFILIACAO_POSSUI VALUES ((SELECT ID_AFILIACAO FROM AFILIACAO WHERE NOME_AFILIACAO='PETROBRAS | PETROLEO BRASILEIRO S/A'), 
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='HAROLDO' AND NOME_DO_MEIO='MARIA TEIXEIRA' AND ULTIMO_NOME='FILHO'));
INSERT INTO PESQUISADOR_AFILIACAO_POSSUI VALUES ((SELECT ID_AFILIACAO FROM AFILIACAO WHERE NOME_AFILIACAO='IBM'), 
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='LEONARDO' AND NOME_DO_MEIO='GUERREIRO' AND ULTIMO_NOME='AZEVEDO'));
INSERT INTO PESQUISADOR_AFILIACAO_POSSUI VALUES ((SELECT ID_AFILIACAO FROM AFILIACAO WHERE NOME_AFILIACAO='PONTIFICIA UNIVERSIDADE CATOLICA DO RIO DE JANEIRO'), 
(SELECT ID_PESQUISADOR FROM PESQUISADOR WHERE PRIMEIRO_NOME='HENRIQUE' AND NOME_DO_MEIO='PRADO' AND ULTIMO_NOME='SOUSA'));


INSERT INTO PUBLICA VALUES ((SELECT ID_PROD_BIBLIO FROM PROD_BIBLIO WHERE TITULO='Governance of Service-Oriented Architecture through the CommonGov Approach'), 
(SELECT ID_REVISTA FROM REVISTA WHERE ISSN='2150-7988'));


COMMIT;