CREATE SEQUENCE SEQ_PESQUISA
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;


CREATE SEQUENCE SEQ_PALAVRA
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;


CREATE SEQUENCE SEQ_PROD_BIBLIO
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;
    
CREATE SEQUENCE SEQ_SITUACAO
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_ED_EV
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;


CREATE SEQUENCE SEQ_EVENTO
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_ESTADO
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_PAIS
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;


CREATE SEQUENCE SEQ_CIDADE
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;


CREATE SEQUENCE SEQ_REVISTA
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;


CREATE SEQUENCE SEQ_COMENT
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;


CREATE SEQUENCE SEQ_PESQUISADOR
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;


CREATE SEQUENCE SEQ_AFILIACAO
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;
        
    
CREATE SEQUENCE SEQ_PROD_BIBLIO_ED_EV_SUBMETE
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;


CREATE TABLE PESQUISA(
ID_PESQUISA NUMBER(6),
NOME_PESQUISA VARCHAR(100) NOT NULL,
ESTAGIO VARCHAR(100) NOT NULL
);




CREATE TABLE PROD_BIBLIO(
ID_PROD_BIBLIO NUMBER (6),
ID_PESQUISA NUMBER(6),
TITULO VARCHAR(255) NOT NULL,
TIPO_PUBLICACAO VARCHAR(100) NOT NULL,
PAGINA_INICIAL NUMBER(4) NOT NULL,
PAGINA_FINAL NUMBER(4) NOT NULL, 
VOLUME NUMBER(3),
ANO_PROD_BIBLIO NUMBER(4) NOT NULL
);


CREATE TABLE PROD_BIBLIO_BASE(
ID_PROD_BIBLIO NUMBER(6),
ID_PROD_BIBLIO_BASE NUMBER(6)
);


CREATE TABLE PALAVRA_CHAVE(
ID_PALAVRA_CHAVE NUMBER(6),
PALAVRA VARCHAR(100) NOT NULL
);


CREATE TABLE PROD_BIBLIO_PALAVRA_CHAVE(
ID_PROD_BIBLIO NUMBER(6),
ID_PALAVRA_CHAVE NUMBER(6)
);





CREATE TABLE PROD_BIBLIO_ED_EVENTO_SUBMETE(
ID_SUBMISSAO NUMBER(6),
ID_PROD_BIBLIO NUMBER(6),
ID_EDICAO_EVENTO NUMBER(6)
);




CREATE TABLE EDICAO_EVENTO(
ID_EDICAO_EVENTO NUMBER(6),
ID_EDICAO_EVENTO_SEQ NUMBER(6),
ID_EVENTO NUMBER(6) NOT NULL,
ANO_EDICAO_EVENTO NUMBER(4) NOT NULL,
ID_CIDADE NUMBER(6),
EDICAO_EVENTO VARCHAR(20) NOT NULL
);

CREATE TABLE EVENTO(
ID_EVENTO NUMBER(6),
NOME_EVENTO VARCHAR(100) NOT NULL,
CLASSIFICACAO_QUALIS VARCHAR(20) DEFAULT 'NAO CLASSIFICADO' NOT NULL,
CLASSIFICACAO VARCHAR(100) NOT NULL
);


CREATE TABLE ESTADO(
ID_ESTADO NUMBER(6),
NOME_ESTADO VARCHAR(50) NOT NULL
);



CREATE TABLE PAIS(
ID_PAIS NUMBER(6),
NOME_PAIS VARCHAR(50) NOT NULL
);


CREATE TABLE CIDADE(
ID_CIDADE NUMBER(6),
ID_PAIS NUMBER(6) NOT NULL,
ID_ESTADO NUMBER(6),
NOME_CIDADE VARCHAR(50) NOT NULL
);


CREATE TABLE REVISTA(
ID_REVISTA NUMBER(6),
ISSN VARCHAR(40) NOT NULL,
CLASSIFICACAO_QUALIS VARCHAR(20) DEFAULT 'NAO CLASSIFICADO' NOT NULL,
NOME_REVISTA VARCHAR(100)
);



CREATE TABLE COMENTARIO(
ID_COMENTARIO NUMBER(6),
ID_PROD_BIBLIO NUMBER(6) NOT NULL,
ID_PESQUISADOR NUMBER(6) NOT NULL,
DATA_COMENTARIO DATE NOT NULL,
COMENTARIO VARCHAR(500) NOT NULL
);


CREATE TABLE PESQUISADOR(
ID_PESQUISADOR NUMBER(6),
PRIMEIRO_NOME VARCHAR(20) NOT NULL,
NOME_DO_MEIO VARCHAR(40),
ULTIMO_NOME VARCHAR(20)NOT NULL,
NUMERO_END_PESQ NUMBER(5) NOT NULL,
LOGRADOURO_PESQ VARCHAR(100) NOT NULL,
TIPO_LOGRADOURO_PESQ VARCHAR(30) NOT NULL,
COMPLEMENTO_PESQ VARCHAR(30)
);


CREATE TABLE PROD_BIBLIO_PESQ_ESCREVE(
ID_PROD_BIBLIO NUMBER(6),
ID_PESQUISADOR NUMBER(6),
NUMERO_ORDEM NUMBER(3) NOT NULL
);


CREATE TABLE PESQUISADOR_CIDADE_RESIDE(
ID_CIDADE NUMBER(6),
ID_PESQUISADOR NUMBER(6)
);


CREATE TABLE AFILIACAO(
ID_AFILIACAO NUMBER(6),
ID_CIDADE NUMBER(6) NOT NULL,
NOME_AFILIACAO VARCHAR(100) NOT NULL,
TIPO_AF VARCHAR(150) NOT NULL,
LOGRADOURO_AF VARCHAR(100) NOT NULL,
TIPO_LOGRADOURO_AF VARCHAR(30) NOT NULL,
NUMERO_END_AF NUMBER(5) NOT NULL,
COMPLEMENTO_AF VARCHAR(30)
);


CREATE TABLE PESQUISADOR_AFILIACAO_POSSUI(
ID_AFILIACAO NUMBER(6),
ID_PESQUISADOR NUMBER(6)
);



CREATE TABLE PUBLICA (
ID_PROD_BIBLIO NUMBER (6),
ID_REVISTA NUMBER (6)
);

CREATE TABLE SITUACAO(
ID_SITUACAO NUMBER(6),
NOME_SITUACAO VARCHAR(100) NOT NULL
);

CREATE TABLE SUBMETE_HIST(
ID_SUBMISSAO NUMBER(6),
ID_SITUACAO NUMBER(6),
DATA_REFERENCIA DATE NOT NULL
);

CREATE TABLE PROD_BIBLIO_HIST(
ID_PROD_BIBLIO NUMBER(6),
ID_SITUACAO NUMBER(6),
DATA_REFERENCIA DATE NOT NULL
);


ALTER TABLE SITUACAO ADD(
 CONSTRAINT SITUACAO_PK PRIMARY KEY(ID_SITUACAO),
 CONSTRAINT SITUACAO_UNQ UNIQUE (NOME_SITUACAO)
 );

ALTER TABLE REVISTA ADD(
 CONSTRAINT REVISTA_PK PRIMARY KEY(ID_REVISTA),
 CONSTRAINT REVISTA_UNQ UNIQUE (ISSN)
 );


ALTER TABLE PESQUISA ADD(
 CONSTRAINT PESQUISA_PK PRIMARY KEY(ID_PESQUISA),
 CONSTRAINT PESQUISA_UNQ UNIQUE (NOME_PESQUISA)
);


ALTER TABLE PROD_BIBLIO ADD(
 CONSTRAINT PROD_BIBLIO_PK PRIMARY KEY(ID_PROD_BIBLIO),
 CONSTRAINT PROD_BIBLIO_2_FK FOREIGN KEY(ID_PESQUISA) REFERENCES PESQUISA(ID_PESQUISA),
 CONSTRAINT PROD_BIBLIO_UNQ UNIQUE (TITULO)
);


ALTER TABLE PROD_BIBLIO_BASE ADD(
CONSTRAINT PROD_BIBLIO_BASE_PK PRIMARY KEY(ID_PROD_BIBLIO,ID_PROD_BIBLIO_BASE),
CONSTRAINT PROD_BIBLIO_BASE_FK FOREIGN KEY (ID_PROD_BIBLIO) REFERENCES PROD_BIBLIO(ID_PROD_BIBLIO),
CONSTRAINT PROD_BIBLIO_BASE_2_FK FOREIGN KEY (ID_PROD_BIBLIO_BASE) REFERENCES PROD_BIBLIO(ID_PROD_BIBLIO)
);


ALTER TABLE PALAVRA_CHAVE ADD(
CONSTRAINT PALAVRA_CHAVE_PK PRIMARY KEY (ID_PALAVRA_CHAVE),
CONSTRAINT PALAVRA_CHAVE_UNQ UNIQUE (PALAVRA)
);


ALTER TABLE PROD_BIBLIO_PALAVRA_CHAVE ADD(
CONSTRAINT PROD_BIBLIO_PALAVRA_CHAVE_PK PRIMARY KEY(ID_PROD_BIBLIO,ID_PALAVRA_CHAVE),
CONSTRAINT PROD_BIBLIO_PALAVRA_CHAVE_FK FOREIGN KEY(ID_PROD_BIBLIO) REFERENCES PROD_BIBLIO(ID_PROD_BIBLIO),
CONSTRAINT PROD_BIBLIO_PALAVRA_CHAVE_2_FK FOREIGN KEY (ID_PALAVRA_CHAVE) REFERENCES PALAVRA_CHAVE(ID_PALAVRA_CHAVE)
);


ALTER TABLE PROD_BIBLIO_HIST ADD(
CONSTRAINT PROD_BIBLIO_HIST_PK PRIMARY KEY(ID_SITUACAO,ID_PROD_BIBLIO),
CONSTRAINT PROD_BIBLIO_HIST_FK FOREIGN KEY (ID_PROD_BIBLIO) REFERENCES PROD_BIBLIO(ID_PROD_BIBLIO),
CONSTRAINT PROD_BIBLIO_HIST_2_FK FOREIGN KEY (ID_SITUACAO) REFERENCES SITUACAO(ID_SITUACAO)
);


ALTER TABLE EVENTO ADD(
CONSTRAINT EVENTO_PK PRIMARY KEY (ID_EVENTO),
CONSTRAINT EVENTO_UNQ UNIQUE (NOME_EVENTO)
);


ALTER TABLE ESTADO ADD(
CONSTRAINT ESTADO_PK PRIMARY KEY(ID_ESTADO),
CONSTRAINT ESTADO_UNQ UNIQUE (NOME_ESTADO)
);


ALTER TABLE PAIS ADD(
CONSTRAINT PAIS_PK PRIMARY KEY (ID_PAIS),
CONSTRAINT PAIS_UNQ UNIQUE (NOME_PAIS)
);


ALTER TABLE CIDADE ADD(
CONSTRAINT CIDADE_PK PRIMARY KEY (ID_CIDADE),
CONSTRAINT CIDADE_FK FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS),
CONSTRAINT CIDADE_2_FK FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO),
CONSTRAINT CIDADE_UNQ UNIQUE (ID_PAIS,NOME_CIDADE)
);


ALTER TABLE EDICAO_EVENTO ADD(
CONSTRAINT EDICAO_EVENTO_PK PRIMARY KEY(ID_EDICAO_EVENTO),
CONSTRAINT EDICAO_EVENTO_FK FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID_EVENTO),
CONSTRAINT EDICAO_EVENTO_UNQ UNIQUE (ID_EVENTO,ANO_EDICAO_EVENTO),
CONSTRAINT EDICAO_EVENTO_2_FK FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID_CIDADE),
CONSTRAINT EDICAO_EVENTO_3_FK FOREIGN KEY (ID_EDICAO_EVENTO_SEQ) REFERENCES EDICAO_EVENTO(ID_EDICAO_EVENTO),
CONSTRAINT EDICAO_EVENTO_2_UNQ UNIQUE (ID_EDICAO_EVENTO_SEQ)
);


ALTER TABLE PROD_BIBLIO_ED_EVENTO_SUBMETE ADD(
CONSTRAINT PROD_BIBLIO_ED_EV_SUB_PK PRIMARY KEY(ID_SUBMISSAO),
CONSTRAINT PROD_BIBLIO_ED_EV_SUB_FK FOREIGN KEY (ID_PROD_BIBLIO) REFERENCES PROD_BIBLIO(ID_PROD_BIBLIO),
CONSTRAINT PROD_BIBLIO_ED_EV_SUB_2_FK FOREIGN KEY (ID_EDICAO_EVENTO) REFERENCES EDICAO_EVENTO(ID_EDICAO_EVENTO),
CONSTRAINT PROD_BIBLIO_ED_EV_SUB_UNQ UNIQUE (ID_PROD_BIBLIO,ID_EDICAO_EVENTO)
);


ALTER TABLE PESQUISADOR ADD(
CONSTRAINT PESQUISADOR_PK PRIMARY KEY (ID_PESQUISADOR),
CONSTRAINT PESQUISADOR_UNQ UNIQUE(PRIMEIRO_NOME,NOME_DO_MEIO,ULTIMO_NOME)
);


ALTER TABLE COMENTARIO ADD(
CONSTRAINT COMENTARIO_PK PRIMARY KEY (ID_COMENTARIO),
CONSTRAINT COMENTARIO_FK FOREIGN KEY (ID_PROD_BIBLIO) REFERENCES PROD_BIBLIO(ID_PROD_BIBLIO),
CONSTRAINT COMENTARIO_2_FK FOREIGN KEY (ID_PESQUISADOR) REFERENCES PESQUISADOR(ID_PESQUISADOR),
CONSTRAINT COMENTARIO_UNQ UNIQUE (ID_PROD_BIBLIO,ID_PESQUISADOR,DATA_COMENTARIO)
);


ALTER TABLE PROD_BIBLIO_PESQ_ESCREVE ADD(
CONSTRAINT PROD_BIBLIO_PESQ_ESCREVE_PK PRIMARY KEY (ID_PROD_BIBLIO,ID_PESQUISADOR),
CONSTRAINT PROD_BIBLIO_PESQ_ESCREVE_FK FOREIGN KEY (ID_PROD_BIBLIO) REFERENCES PROD_BIBLIO(ID_PROD_BIBLIO),
CONSTRAINT PROD_BIBLIO_PESQ_ESCREVE_2_FK FOREIGN KEY (ID_PESQUISADOR) REFERENCES PESQUISADOR (ID_PESQUISADOR)
);


ALTER TABLE PESQUISADOR_CIDADE_RESIDE ADD(
CONSTRAINT PESQUISADOR_CIDADE_RESIDE_PK PRIMARY KEY (ID_CIDADE,ID_PESQUISADOR),
CONSTRAINT PESQUISADOR_CIDADE_RESIDE_FK FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID_CIDADE),
CONSTRAINT PESQUISADOR_CIDADE_RESIDE_2_FK FOREIGN KEY (ID_PESQUISADOR) REFERENCES PESQUISADOR(ID_PESQUISADOR)
);


ALTER TABLE AFILIACAO ADD(
CONSTRAINT AFILIACAO_PK PRIMARY KEY (ID_AFILIACAO),
CONSTRAINT AFILIACAO_FK FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID_CIDADE),
CONSTRAINT AFILIACAO_UNQ UNIQUE (NOME_AFILIACAO)
);


ALTER TABLE PESQUISADOR_AFILIACAO_POSSUI ADD(
CONSTRAINT PESQ_AF_POSSUI_PK PRIMARY KEY(ID_AFILIACAO,ID_PESQUISADOR),
CONSTRAINT PESQ_AF_POSSUI_FK FOREIGN KEY(ID_AFILIACAO) REFERENCES AFILIACAO(ID_AFILIACAO),
CONSTRAINT PESQ_AF_POSSUI_2_FK FOREIGN KEY(ID_PESQUISADOR) REFERENCES PESQUISADOR(ID_PESQUISADOR)
);

ALTER TABLE SUBMETE_HIST ADD(
CONSTRAINT SUBMETE_HIST_PK PRIMARY KEY(ID_SUBMISSAO,ID_SITUACAO),
CONSTRAINT SUBMETE_HIST_FK FOREIGN KEY (ID_SUBMISSAO) REFERENCES PROD_BIBLIO_ED_EVENTO_SUBMETE(ID_SUBMISSAO),
CONSTRAINT SUBMETE_HIST_2_FK FOREIGN KEY (ID_SITUACAO) REFERENCES SITUACAO(ID_SITUACAO)
);

